### ISSUE TITLE
微博第三方客户端 奇点 有的图片显示不出

### ISSUE THREAD

**Issue by zywsss** [icodesign/Potatso-Project#104]
### 问题描述
同一条微博的不同图片，有的图片刷不出。我把规则清空，默认路由选DIRECT，重新连接potatso，还是存在这个问题，所以可以排除规则问题。排除wifi问题，在移动4G下也会出现同样情况。

### Potatso 版本
2.2.1.179

### iOS 系统版本
iphone6 10.3.1

![_20170428105816](https://cloud.githubusercontent.com/assets/25564085/25512709/5cc41b2a-2c02-11e7-8901-18f778a02b49.jpg)

点击缩略图后，也是加载不了图片

![_20170428105827](https://cloud.githubusercontent.com/assets/25564085/25512598/a08bf7ac-2c01-11e7-8bf0-54872c838294.jpg)

**Comment by icodesign** [comment]
在最新的 TF (2.2.2.182)中已修复

**Comment by zywsss** [comment]
更新最新的商店版2.2.2后，这个问题出现的情况少了一些，不过依然还是会出现。

**Comment by icodesign** [comment]
感谢反馈，我再观察下

**Comment by zywsss** [comment]
看了下，显示不出的，好像都发生在gif的动图上。

**Comment by zywsss** [comment]
还有长图也显示不出

**Comment by icodesign** [comment]
直连吗？

**Comment by zywsss** [comment]
嗯，规则清空，默认路由DIRECT，刚才手机和电脑端对应着看了下，gif和长图是全部显示不出的，普通的图，有很少也显示不出。

**Comment by icodesign** [comment]
观察一下官方客户端是否有类似行为

**Comment by zywsss** [comment]
官方客户端 有缩略图没显示的，不过点开又能点开的。奇点是点开也无法显示。

**Comment by icodesign** [comment]
确实还是有点问题，目前重试几次可以解决问题，我再研究一下

**Comment by zywsss** [comment]
好的
